FROM continuumio/miniconda3:4.10.3
MAINTAINER Mingxun Wang "mwang87@gmail.com"

RUN apt-get update && apt-get install -y build-essential

RUN conda install -c conda-forge mamba
RUN mamba create -n rdkit -c rdkit rdkit=2020.09.1.0

COPY requirements.txt /

RUN /bin/bash -c ". activate rdkit && pip install -r requirements.txt"


COPY . /app
WORKDIR /app